import Head from "next/head"
import "../styles/globals.css"


function MyApp({ Component, pageProps }) {

  // Use the layout defined at the page level, if available:
  const getLayout = Component.getLayout || ((page) => page)

  return(
    <>
      <Head>
        <title>Tabula Rasa: HeadlessUI Edition</title>
        <link
          rel="icon"
          href="/favicon.ico"
        />
        <meta name="description" content="Generated by create next app" />
      </Head>
      { getLayout( <Component {...pageProps} /> ) }
    </>
  ) 
}

export default MyApp
