import Head from "next/head"
// import Image from "next/image"
// import styles from "../styles/index.module.css"
import { Container, Divider } from "semantic-ui-react"

import Footer from "../components/Footer.js"
import Header from "../components/Header.js"
import SampleTable from "../components/SampleTable.js"

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Tabula Rasa - Next.js</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <Container>
        <header>
          <Header />
        </header>

        <main className="">
          <Container>
            <SampleTable />
          </Container>
        </main>

        <footer className="">
          <Footer />
        </footer>
      </Container>
    </div>
  )
}
